#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
umask 077

ENVIRONMENT="${1:?environment is required: stage or prod}"
CONFIG_FILE="/etc/lexigo/certificate-health-${ENVIRONMENT}.conf"
RENEW_BEFORE_SECONDS="${CERT_RENEW_BEFORE_SECONDS:-1814400}"

log() {
  printf '[certificate-health] %s\n' "$*"
}

die() {
  printf '[certificate-health] ERROR: %s\n' "$*" >&2
  exit 1
}

case "$ENVIRONMENT" in
  stage|prod) ;;
  *) die "unsupported environment: $ENVIRONMENT" ;;
esac

[[ -r "$CONFIG_FILE" ]] || die "configuration is missing: $CONFIG_FILE"
# The file is generated by remote-deploy.sh, owned by root and mode 0600.
# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${PROJECT_ROOT:?PROJECT_ROOT is required}"
: "${COMPOSE_FILE:?COMPOSE_FILE is required}"
: "${APP_ENV_FILE:?APP_ENV_FILE is required}"
: "${SITE_HOST:?SITE_HOST is required}"
: "${API_HOST:?API_HOST is required}"

[[ "$PROJECT_ROOT" == /opt/* ]] || die "PROJECT_ROOT must be below /opt"
[[ "$COMPOSE_FILE" == "$PROJECT_ROOT/"* ]] || die "COMPOSE_FILE must be below PROJECT_ROOT"
[[ "$APP_ENV_FILE" == "$PROJECT_ROOT/"* ]] || die "APP_ENV_FILE must be below PROJECT_ROOT"
[[ "$SITE_HOST" =~ ^[A-Za-z0-9.-]+$ ]] || die "SITE_HOST is invalid"
[[ "$API_HOST" =~ ^[A-Za-z0-9.-]+$ ]] || die "API_HOST is invalid"
[[ "$RENEW_BEFORE_SECONDS" =~ ^[0-9]+$ ]] || die "CERT_RENEW_BEFORE_SECONDS must be numeric"

cd "$PROJECT_ROOT"
COMPOSE=(docker compose --env-file "$APP_ENV_FILE" -f "$COMPOSE_FILE")

certificate_pem() {
  local host="$1"
  timeout 20 openssl s_client \
    -connect 127.0.0.1:443 \
    -servername "$host" \
    -showcerts \
    </dev/null 2>/dev/null \
    | awk '
        /-----BEGIN CERTIFICATE-----/ { capture=1 }
        capture { print }
        /-----END CERTIFICATE-----/ { exit }
      '
}

check_host() (
  local host="$1"
  local certificate_file
  certificate_file="$(mktemp)"
  trap 'rm -f -- "$certificate_file"' EXIT

  curl \
    --fail \
    --silent \
    --show-error \
    --max-time 20 \
    --resolve "$host:443:127.0.0.1" \
    "https://$host/health/ready" \
    >/dev/null

  certificate_pem "$host" > "$certificate_file"
  [[ -s "$certificate_file" ]] || return 1
  openssl x509 -in "$certificate_file" -noout -checkhost "$host" >/dev/null
  openssl x509 -in "$certificate_file" -noout -checkend "$RENEW_BEFORE_SECONDS" >/dev/null
)

check_all() {
  check_host "$SITE_HOST" && check_host "$API_HOST"
}

if check_all; then
  log "TLS certificates are valid for more than $RENEW_BEFORE_SECONDS seconds"
  exit 0
fi

log "TLS validation failed or a certificate is near expiry; restarting Caddy to trigger managed renewal"
"${COMPOSE[@]}" build --pull caddy
"${COMPOSE[@]}" up -d --no-deps --build caddy

for attempt in $(seq 1 18); do
  if check_all; then
    log "TLS certificates are healthy after Caddy renewal attempt"
    exit 0
  fi
  sleep 5
done

"${COMPOSE[@]}" ps caddy || true
"${COMPOSE[@]}" logs --tail=200 caddy || true
die "TLS certificates are still unhealthy after the renewal attempt"
