import { createHash } from "node:crypto";

import {
  expect,
  test,
  type BrowserContext,
  type Page,
  type Route,
  type TestInfo,
} from "@playwright/test";

import {
  installActiveLessonFixture,
  openActiveLesson,
} from "./support/active-lesson-fixture";
import {
  captureRuntimeErrors,
  installDeterministicRuntime,
  installQualityGateAPI,
  QUALITY_PHRASES,
  QUALITY_SESSION,
} from "./support/quality-gates";
import {
  CANONICAL_WORD_DETAIL,
  installCanonicalWordDetailFixture,
} from "./support/word-detail-fixture";

type ExplicitAppearance = "light" | "dark";
type RouteParityKey =
  | "home"
  | "learn"
  | "active-lesson"
  | "progress"
  | "dictionary"
  | "word-detail"
  | "phrases"
  | "phrase-detail"
  | "profile"
  | "onboarding";

type RouteParityContract = Readonly<{
  key: RouteParityKey;
  path: string;
  ownerSelector: string;
  focused: boolean;
}>;

type RouteVisualBaseline = Readonly<{
  width: number;
  height: number;
  sha256: string;
  sourceRun: number;
  sourceHeadSha: string;
}>;

type RouteViewport = Readonly<{
  width: number;
  height: number;
  label: string;
}>;

const MIN_MOBILE_VIEWPORT: RouteViewport = {
  width: 320,
  height: 700,
  label: "320×700",
};

const TABLET_VIEWPORT: RouteViewport = {
  width: 768,
  height: 1024,
  label: "768×1024",
};

const DESKTOP_VIEWPORT: RouteViewport = {
  width: 1440,
  height: 1024,
  label: "1440×1024",
};

const ROUTE_PARITY_ROUTES: readonly RouteParityContract[] = [
  { key: "home", path: "/", ownerSelector: '[data-route-client-island="home"]', focused: false },
  { key: "learn", path: "/learn", ownerSelector: '[data-route-client-island="learn"]', focused: false },
  { key: "active-lesson", path: "/lesson/active", ownerSelector: '[data-route-client-island="active-lesson"]', focused: true },
  { key: "progress", path: "/progress", ownerSelector: '[data-route-client-island="progress"]', focused: false },
  { key: "dictionary", path: "/dictionary", ownerSelector: '[data-route-client-island="dictionary"]', focused: false },
  { key: "word-detail", path: "/words/101", ownerSelector: '[data-route-client-island="dictionary"]', focused: false },
  { key: "phrases", path: "/phrases", ownerSelector: '[data-route-client-island="phrases"]', focused: false },
  { key: "phrase-detail", path: `/phrases/${QUALITY_PHRASES[0].slug}`, ownerSelector: '[data-route-client-island="phrases"]', focused: false },
  { key: "profile", path: "/profile", ownerSelector: '[data-route-client-island="profile"]', focused: false },
  { key: "onboarding", path: "/onboarding", ownerSelector: ".lx-first-use-panel", focused: true },
] as const;

/**
 * Issue #587 exact Linux minimum-width evidence was generated by diagnostic
 * CI #3778 / run 32119608484 on head
 * 092a578bcf04e3ab7d4bcb98038535797058b011. All 20 Light/Dark states reached
 * the deliberate REVIEW_REQUIRED gate only after route ownership,
 * reduced-motion, geometry/overflow/focus and runtime-error assertions passed.
 * Artifact #9318281585 (digest
 * sha256:6066e9fc393afe1f1052cdf836d63a645df2e1f3b65d10972e9ab7da9094ac20)
 * was downloaded and every exact 320×700 PNG was manually reviewed after the
 * #589 Learn contrast and #590 Phrase Detail width repairs. Initial/retry
 * captures were byte-stable for every state.
 */
const MIN_MOBILE_VISUAL_BASELINES: Record<
  `${RouteParityKey}.${ExplicitAppearance}`,
  RouteVisualBaseline
> = {
  "home.light": { width: 320, height: 956, sha256: "cedd4ed0db0f23f6738599c7e500b9dd01ca26fb88bcebec3e3915726d4aebd1", sourceRun: 32635302334, sourceHeadSha: "77ca1ea56e23b058eeb2786524617797aaa18d47" },
  "home.dark": { width: 320, height: 956, sha256: "53a35494a8a7cc74bb608bdf300f17fe2935abfbc51c2f5cc397d39c8ad092c7", sourceRun: 32635302334, sourceHeadSha: "77ca1ea56e23b058eeb2786524617797aaa18d47" },
  "learn.light": { width: 320, height: 1366, sha256: "341170addd801f2bd93755ea7879b7e88e2d7fd18e791a16337b6070e3db1dc3", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "learn.dark": { width: 320, height: 1366, sha256: "99714f5b3ffdd1aa0a4e81a4afdd2930cf24fa099a613aafd1fdaf486c769e2c", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "active-lesson.light": { width: 320, height: 758, sha256: "d0e1025de310cec9270ba1e3215141d51c53b8e2e8604b78c360dfc525665f12", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "active-lesson.dark": { width: 320, height: 758, sha256: "8d8b73841a92770f1d481a5dd2e2fae22482e72a71004fada93d551478e3bcac", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "progress.light": { width: 320, height: 2291, sha256: "19d764f16f3781ca4e59b281b131c1069cfd964af4d69b4dde39b9742e0fae25", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "progress.dark": { width: 320, height: 2291, sha256: "fb7fd60bc5c250a29a1760b4d07d3c50904bc93c36b0fa4df80fea237d5dc5c9", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "dictionary.light": { width: 320, height: 1387, sha256: "611bbfa2f78a0597255e8d7d77ccbd85c8c09102dd1d9d7a82df493a90dc7d85", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "dictionary.dark": { width: 320, height: 1387, sha256: "0462141cde446856e0d6ee3cc9af6e9e8fc6a1447859c51520871ba94d8fc245", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "word-detail.light": { width: 320, height: 1961, sha256: "9cf68d3125396e327994928fddc73e1b57101bf67c17dd81c6b144622b9b60f7", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "word-detail.dark": { width: 320, height: 1961, sha256: "396e22dbcba3f528771cbe79492241ffd573dc157a8185ad800fa237f63d9e2d", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "phrases.light": { width: 320, height: 1834, sha256: "dd51a31836fd8414b12f23d19414a1015e769e936febfd98c69433cb0d592412", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "phrases.dark": { width: 320, height: 1834, sha256: "d3edd17c06ac97cf8735d0e3f3b36db05a438eefb7450e69235db4f9cf3814eb", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "phrase-detail.light": { width: 320, height: 2149, sha256: "fc4e5d977344e67990f9b2233e36e1e7449a2f6da94ba31977cd16e9a0ccea1d", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "phrase-detail.dark": { width: 320, height: 2149, sha256: "2c9fa021011fbf12bff409f48483c9f842e4333aaf4ddc6e36e6c122e4ad8d8b", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "profile.light": { width: 320, height: 5838, sha256: "c8e6f03f00b90dc0a8d28e710602c6e69d46a1b472ff8d2698f66e3b6dc1996f", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "profile.dark": { width: 320, height: 5838, sha256: "1d1657d7300a866546340840a8d65c039c4c39c10d4f60a927f18e3c38caaab1", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "onboarding.light": { width: 320, height: 984, sha256: "d32c8b47a4a98e63d80cf6bd6da3c51ee5d52946a95c10f601b8484d0d69f3a1", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
  "onboarding.dark": { width: 320, height: 984, sha256: "f834a935f9be001bd4c13deebcc00b2ec40031456badf8240399b9df6665c87f", sourceRun: 32119608484, sourceHeadSha: "092a578bcf04e3ab7d4bcb98038535797058b011" },
};

/**
 * The original 20-state matrix was manually reviewed from exact Linux artifact
 * #9291962719 / CI 32040684330. Issue #577 intentionally changed shared RouteChrome
 * Reminder presentation; the 14 non-focused states that expose that owner were
 * re-reviewed from exact Linux artifact #9294131591 / CI 32048818693 on head
 * be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25. Unaffected focused/word-detail/
 * onboarding states retain their earlier reviewed fingerprints. Retries were
 * byte-stable for every changed state.
 */
const TABLET_VISUAL_BASELINES: Record<
  `${RouteParityKey}.${ExplicitAppearance}`,
  RouteVisualBaseline
> = {
  "home.light": { width: 768, height: 1105, sha256: "f7836426dc58452dbf2368243a99b106ff6df56a8fb1864eb7082689ae059006", sourceRun: 32635302334, sourceHeadSha: "77ca1ea56e23b058eeb2786524617797aaa18d47" },
  "home.dark": { width: 768, height: 1105, sha256: "5bd2f146f2919f8a1dab8549b2d7c78159d28c35d5c5a26aa02bce568260af24", sourceRun: 32635302334, sourceHeadSha: "77ca1ea56e23b058eeb2786524617797aaa18d47" },
  "learn.light": { width: 768, height: 1990, sha256: "93ac0782063716b42945f7aedd976215c53935f60f0f1f4e0992645df77b2555", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "learn.dark": { width: 768, height: 1990, sha256: "ab36aebf46a17830df6eba4fb60f92fd0ead4d04ef1c15ff35c94519fb74ead6", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "active-lesson.light": { width: 768, height: 1024, sha256: "39dbd304a26668f6a11acb774d7e790cab4ba51af2710b0fc42a00631b104998", sourceRun: 32040684330, sourceHeadSha: "3578718bdcba1a24873ce23999ef7672a22193c5" },
  "active-lesson.dark": { width: 768, height: 1024, sha256: "4f02aaef1849bee10c6a3bc71a72dba26ee2cb3615e12030c6eead00281cf935", sourceRun: 32040684330, sourceHeadSha: "3578718bdcba1a24873ce23999ef7672a22193c5" },
  "progress.light": { width: 768, height: 1689, sha256: "c097a3e74f7e5e49781fb5d5d051e0acd528eaa3d289940db4a58817c8d4e7fc", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "progress.dark": { width: 768, height: 1689, sha256: "22bbbee0ef240cdc99678248ca5a9012e0a3bfe5aa41e2e8513f2ad8cf7211e3", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "dictionary.light": { width: 768, height: 1760, sha256: "276b5066a4561f266ad65d9178dba27c4b13b8b23cf1a5736c8e1666236f3727", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "dictionary.dark": { width: 768, height: 1760, sha256: "d5a941d0404c27b1df5b1fd1c199dcaeeb6b61620ea3323363d84d5a57ad4eaf", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "word-detail.light": { width: 768, height: 1663, sha256: "e065b923b788c332735b40370c61734eb5fc4e59bdb98f5ee0a5ee1c7556deb8", sourceRun: 32040684330, sourceHeadSha: "3578718bdcba1a24873ce23999ef7672a22193c5" },
  "word-detail.dark": { width: 768, height: 1663, sha256: "d625844b0762103dc08a910dd994db0d0001ca7466691d779539d32945bf796a", sourceRun: 32040684330, sourceHeadSha: "3578718bdcba1a24873ce23999ef7672a22193c5" },
  "phrases.light": { width: 768, height: 1593, sha256: "1888474ef81dc4f577eb6d60e7824345633f5fd00d85ee317f9906e29e1da30e", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "phrases.dark": { width: 768, height: 1593, sha256: "b121949056aed463ee7bacb94b8425764989fdb11d4c9243d532d0c192e7c98a", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "phrase-detail.light": { width: 768, height: 1496, sha256: "37d20ed62bda48c5c3378ce35d5b617cd36562fab02de66fc56a5cd2f27677dc", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "phrase-detail.dark": { width: 768, height: 1496, sha256: "aea943afe911220248920857412f0014a12506d2362b2ef9d71cf7d34c86d0be", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "profile.light": { width: 768, height: 4229, sha256: "4e03f171ad8dca2abfff40fd1e1368b9a42358de72d653b66fd4209a1b34bde4", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "profile.dark": { width: 768, height: 4229, sha256: "e8c4a7a37df7d1227212915ab083611097bbb63a65933462a267d02c752ab1af", sourceRun: 32048818693, sourceHeadSha: "be2bf0341bc85bdb3f860e5e7ba3226f2cedbc25" },
  "onboarding.light": { width: 768, height: 1024, sha256: "b63d5ec40e59cf210db08a2edb5134a529adb62653b8dd751da91472d01f010a", sourceRun: 32040684330, sourceHeadSha: "3578718bdcba1a24873ce23999ef7672a22193c5" },
  "onboarding.dark": { width: 768, height: 1024, sha256: "483efada706044601cd599aea9e7c76c0e71da176578a610740c666bfd620aad", sourceRun: 32040684330, sourceHeadSha: "3578718bdcba1a24873ce23999ef7672a22193c5" },
};

/**
 * Issue #581 exact Linux evidence was generated by CI #3746 / run 32065112367
 * on diagnostic head 244a71b6202b3f22e51e46c9fccc7cc385cf92ad. All 20
 * Light/Dark states reached the deliberate REVIEW_REQUIRED gate only after
 * route ownership, reduced-motion, geometry/overflow/focus and runtime-error
 * assertions passed. Artifact #9299858153 (digest
 * sha256:ce2451443302b3de5e1a6ed7aeee3a94b9124e2985b4ace32fb3a8e881499e87)
 * was downloaded and every exact PNG was manually reviewed before approval.
 * Initial/retry captures were byte-stable for every state.
 */
const DESKTOP_VISUAL_BASELINES: Record<
  `${RouteParityKey}.${ExplicitAppearance}`,
  RouteVisualBaseline
> = {
  "home.light": { width: 1440, height: 1105, sha256: "b37b4a1d920e759801a69957d9f4c5e945066b36db0e5a6f9bbbf2bcc5586580", sourceRun: 32635302334, sourceHeadSha: "77ca1ea56e23b058eeb2786524617797aaa18d47" },
  "home.dark": { width: 1440, height: 1105, sha256: "e9142aab3d15352b550032b1162843d8b10b3ede7d55198a5906b194f7607fec", sourceRun: 32635302334, sourceHeadSha: "77ca1ea56e23b058eeb2786524617797aaa18d47" },
  "learn.light": { width: 1440, height: 1656, sha256: "d196e015be4edaeb962a958e03d16bc053215421fa017cc899602bac627a201c", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "learn.dark": { width: 1440, height: 1656, sha256: "9e736276cfa95789ca51daecb0853281bafcf239ede3e035cefcfb2c6a8dfd4e", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "active-lesson.light": { width: 1440, height: 1024, sha256: "2d33261eddb56ed40d3819883ed079a0633b61b4c69ff1259a672f43e17776a0", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "active-lesson.dark": { width: 1440, height: 1024, sha256: "e154e96f327b7632302ef511a806e189e556519ee04b52dc2b7f389c7ad77677", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "progress.light": { width: 1440, height: 1117, sha256: "8b9fad8449afaea04099bab21a54d06d60486634b7911d3ce4450a6a966cd400", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "progress.dark": { width: 1440, height: 1117, sha256: "9e79ac852a76d6e3b14081285f399e2bfca059e1d0ebc44c303672e78b661b73", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "dictionary.light": { width: 1440, height: 1720, sha256: "c54ddbb7cd150a569c3f584a6f9339e6366d87b8e6ede7359dca427c06b5e462", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "dictionary.dark": { width: 1440, height: 1720, sha256: "e667ea9857334bcad0531c923290493f32b01bf90ce31f787fac37d2a57949f7", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "word-detail.light": { width: 1440, height: 1160, sha256: "dfafb7afc0bbf30d1da49a1bd725fc4d3f9f430a37aadc2fcc907d2385cfb945", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "word-detail.dark": { width: 1440, height: 1160, sha256: "27d509c0e7d0fdb3b958aacd8131e082c61ef184fd71b11f05de318b0509dfbe", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "phrases.light": { width: 1440, height: 1185, sha256: "cb03cc6def171553bd0d5c2b2f82f844566da1b71f8a47daf008b3ee56acb26b", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "phrases.dark": { width: 1440, height: 1185, sha256: "7f56e79aa8af9bbf864c19134d5870c31a27809776eaa141b9a2af633aea68fd", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "phrase-detail.light": { width: 1440, height: 1413, sha256: "d731e567e42da7e2254cb6fb711acb6dc139757bfbb1c4f8a5f5746ecd27f76b", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "phrase-detail.dark": { width: 1440, height: 1413, sha256: "e21039e2ccfc04b39c327adf909ca4b8ff1ae1866430d7baadfa16eb8fd36d5e", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "profile.light": { width: 1440, height: 3345, sha256: "089d99e2444b0f787740ed7d9c6d2e752de05a2bfdf8f6398574de013f68a786", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "profile.dark": { width: 1440, height: 3345, sha256: "40fe9e7caa3dac552797a3ba7fadaf89782857461f475724a7b83eddcee87b87", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "onboarding.light": { width: 1440, height: 1024, sha256: "2036da15f83b7d8f0eaf714f2f5ad92237dc7c35a3c89216559845805ea9fda8", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
  "onboarding.dark": { width: 1440, height: 1024, sha256: "5337ece0239890d77329406e5069558d73c0f8bb70e83692e14e58c81ef50704", sourceRun: 32065112367, sourceHeadSha: "244a71b6202b3f22e51e46c9fccc7cc385cf92ad" },
};

const ONBOARDING_PROMPT = {
  position: 4,
  id: 20101,
  kind: "word",
  lemma: "schema evolution",
  phonetic: "/ˈskiːmə/",
  partOfSpeech: "noun",
  topic: "Data Engineering",
};

async function fulfillJSON(route: Route, status: number, body: unknown): Promise<void> {
  await route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

async function installAppearance(page: Page, appearance: ExplicitAppearance): Promise<void> {
  await page.addInitScript((value) => {
    window.localStorage.setItem("lexigo.appearance.v1", value);
  }, appearance);
  await page.emulateMedia({
    colorScheme: appearance,
    reducedMotion: "reduce",
  });
}

async function installOnboardingResumeAPI(context: BrowserContext): Promise<void> {
  // The shared quality-gate API intentionally does not own the onboarding state
  // machine. Replace only this test context's API route with the already-delivered
  // #18 resume contract used by the canonical First Use visual suite.
  await context.unroute("**/api/v1/**");
  await context.addCookies([{
    name: "lexigo_csrf",
    value: "tablet-parity-csrf",
    url: "http://127.0.0.1:3000",
    sameSite: "Lax",
  }]);

  await context.route("**/api/v1/**", async (route) => {
    const request = route.request();
    const path = new URL(request.url()).pathname;

    if (path === "/api/v1/auth/refresh") return fulfillJSON(route, 200, QUALITY_SESSION);
    if (path === "/api/v1/auth/sessions") return fulfillJSON(route, 200, { sessions: [] });
    if (path === "/api/v1/onboarding" && request.method() === "GET") {
      return fulfillJSON(route, 200, {
        state: "in_progress",
        total: 12,
        marked: 4,
        current: ONBOARDING_PROMPT,
      });
    }

    return fulfillJSON(route, 404, {
      error: { code: "not_mocked", message: path },
    });
  });
}

async function openParityRoute(
  contract: RouteParityContract,
  page: Page,
  context: BrowserContext,
): Promise<void> {
  switch (contract.key) {
    case "home":
      await page.goto("/", { waitUntil: "domcontentloaded" });
      await expect(page.getByRole("heading", {
        name: /Продолжите с сохранённой позиции|готов(?:ы)? к повторению|Добавьте новые слова|Соберите первый учебный блок|Настройте урок под текущую задачу/,
      })).toBeVisible();
      return;
    case "learn":
      await page.goto("/learn", { waitUntil: "domcontentloaded" });
      await expect(page.getByRole("heading", { name: "Соберите один сфокусированный урок" })).toBeVisible();
      return;
    case "active-lesson":
      await installActiveLessonFixture(page, "recall");
      await openActiveLesson(page);
      await expect(page.locator(".lx-active-lesson")).toHaveAttribute("data-active-lesson-state", "prompt");
      return;
    case "progress":
      await page.goto("/progress", { waitUntil: "domcontentloaded" });
      await expect(
        page.locator(".lx-progress-evidence").getByRole("heading", { name: "Прогресс", exact: true }),
      ).toBeVisible();
      return;
    case "dictionary":
      await page.goto("/dictionary", { waitUntil: "domcontentloaded" });
      await expect(page.getByRole("heading", { level: 1, name: "Словарь", exact: true })).toBeVisible();
      await expect(page.getByRole("button", { name: "Открыть карточку: rollback" })).toBeVisible();
      return;
    case "word-detail":
      await installCanonicalWordDetailFixture(page);
      await page.goto("/words/101?source=backend&topic=Release&status=review&page=2", {
        waitUntil: "domcontentloaded",
      });
      await expect(page.getByRole("heading", { level: 1, name: CANONICAL_WORD_DETAIL.lemma })).toBeVisible();
      await expect(page.getByText("Следующее повторение", { exact: true })).toBeVisible();
      return;
    case "phrases":
      await page.goto("/phrases", { waitUntil: "domcontentloaded" });
      await expect(page.getByRole("heading", { level: 1, name: "Находите готовые формулировки" })).toBeVisible();
      await expect(
        page.getByRole("list", { name: "Результаты каталога фраз" }).getByRole("listitem"),
      ).toHaveCount(QUALITY_PHRASES.length);
      return;
    case "phrase-detail":
      await page.goto(`/phrases/${QUALITY_PHRASES[0].slug}`, { waitUntil: "domcontentloaded" });
      await expect(page.getByRole("heading", { level: 1, name: QUALITY_PHRASES[0].lemma })).toBeVisible();
      return;
    case "profile":
      await page.goto("/profile", { waitUntil: "domcontentloaded" });
      await expect(page.getByRole("heading", { level: 1, name: "Профиль", exact: true })).toBeVisible();
      await expect(page.getByText("12 из 30 ответов сегодня", { exact: true })).toBeVisible();
      return;
    case "onboarding": {
      await installOnboardingResumeAPI(context);
      await page.goto("/onboarding", { waitUntil: "domcontentloaded" });
      await expect(page.getByRole("heading", { name: "Продолжим диагностику" })).toBeVisible();
      const unsureMark = page.getByRole("radio", { name: "Не уверен" });
      await unsureMark.click();
      await expect(unsureMark).toHaveAttribute("aria-checked", "true");
      return;
    }
  }
}

async function settleParityRoute(page: Page, appearance: ExplicitAppearance): Promise<void> {
  await expect(page.locator("html")).toHaveAttribute("data-lexigo-appearance", appearance);
  await expect(page.locator("html")).toHaveAttribute("data-lexigo-resolved-appearance", appearance);
  await page.evaluate(async () => {
    await document.fonts.ready;
    window.scrollTo({ top: 0, behavior: "auto" });
  });
  await page.waitForTimeout(100);
}

async function expectParityOwnership(
  page: Page,
  contract: RouteParityContract,
  viewport: RouteViewport,
  forbidLegacyCompatibilityOwner = false,
): Promise<void> {
  await expect(page).toHaveURL((url) => url.pathname === contract.path);
  await expect(page.locator(contract.ownerSelector)).toBeVisible();
  await expect(page.locator("#lexigo-main-content")).toBeVisible();
  expect(
    await page.evaluate(() => window.matchMedia("(prefers-reduced-motion: reduce)").matches),
    `${contract.key} must run with reduced motion at ${viewport.label}`,
  ).toBe(true);

  const geometry = await page.evaluate((input) => {
    const root = document.documentElement;
    const main = document.querySelector<HTMLElement>("#lexigo-main-content");
    const owner = document.querySelector<HTMLElement>(input.ownerSelector);
    if (!main || !owner) throw new Error(`Route parity owner is not mounted: ${input.ownerSelector}`);

    const rect = (node: HTMLElement) => {
      const box = node.getBoundingClientRect();
      return {
        left: box.left,
        right: box.right,
        top: box.top,
        bottom: box.bottom,
        width: box.width,
        height: box.height,
      };
    };

    const isRendered = (node: HTMLElement) => {
      const style = window.getComputedStyle(node);
      const box = node.getBoundingClientRect();
      return style.display !== "none"
        && style.visibility !== "hidden"
        && style.visibility !== "collapse"
        && Number.parseFloat(style.opacity || "1") > 0
        && box.width > 0
        && box.height > 0;
    };

    const visibleNavigation = Array.from(
      document.querySelectorAll<HTMLElement>("[data-route-navigation]"),
    )
      .map((node) => {
        const style = window.getComputedStyle(node);
        return {
          variant: node.dataset.routeNavigation ?? "",
          display: style.display,
          visibility: style.visibility,
          box: rect(node),
        };
      })
      .filter((item) => (
        item.display !== "none"
        && item.visibility !== "hidden"
        && item.box.width > 0
        && item.box.height > 0
      ));

    const legacyCompatibilityOwners = Array.from(
      document.querySelectorAll<HTMLElement>('[data-route-client-island="product"]'),
    )
      .filter(isRendered)
      .map((node) => rect(node));

    const focusableSelector = [
      "a[href]",
      "button",
      "input",
      "select",
      "textarea",
      "summary",
      "[tabindex]:not([tabindex='-1'])",
    ].join(",");
    const focusableOffenders = Array.from(
      document.querySelectorAll<HTMLElement>(focusableSelector),
    ).flatMap((node) => {
      const style = window.getComputedStyle(node);
      const box = node.getBoundingClientRect();
      const rendered = style.display !== "none"
        && style.visibility !== "hidden"
        && style.visibility !== "collapse"
        && Number.parseFloat(style.opacity || "1") > 0
        && box.width > 0
        && box.height > 0;
      if (!rendered) return [];

      // Controls fully outside the viewport may belong to an intentional
      // horizontal scroller. Partially visible focusable controls must keep the
      // complete focus box inside the viewport.
      const intersectsViewport = box.right > 0 && box.left < root.clientWidth;
      if (!intersectsViewport) return [];
      if (box.left >= -1 && box.right <= root.clientWidth + 1) return [];

      return [{
        tag: node.tagName.toLowerCase(),
        id: node.id,
        label: node.getAttribute("aria-label")
          ?? node.getAttribute("title")
          ?? node.textContent?.trim().replace(/\s+/g, " ").slice(0, 80)
          ?? "",
        left: box.left,
        right: box.right,
        width: box.width,
      }];
    });

    return {
      innerWidth: window.innerWidth,
      innerHeight: window.innerHeight,
      clientWidth: root.clientWidth,
      documentWidth: Math.max(root.scrollWidth, document.body.scrollWidth),
      main: rect(main),
      owner: rect(owner),
      visibleNavigation,
      legacyCompatibilityOwners,
      focusableOffenders,
    };
  }, { ownerSelector: contract.ownerSelector });

  expect(geometry.innerWidth).toBe(viewport.width);
  expect(geometry.innerHeight).toBe(viewport.height);
  expect(
    geometry.documentWidth,
    `${contract.key} must not overflow horizontally at ${viewport.label}`,
  ).toBeLessThanOrEqual(geometry.clientWidth + 1);

  for (const [label, owner] of [["main", geometry.main], ["route owner", geometry.owner]] as const) {
    expect(owner.width, `${contract.key} ${label} must have positive width`).toBeGreaterThan(0);
    expect(owner.left, `${contract.key} ${label} must not clip on the inline start`).toBeGreaterThanOrEqual(-1);
    expect(owner.right, `${contract.key} ${label} must not clip on the inline end`).toBeLessThanOrEqual(geometry.clientWidth + 1);
  }

  if (forbidLegacyCompatibilityOwner) {
    expect(
      geometry.legacyCompatibilityOwners,
      `${contract.key} must not expose the legacy compatibility route owner at ${viewport.label}`,
    ).toEqual([]);
  }
  expect(
    geometry.focusableOffenders,
    `${contract.key} must not partially clip rendered focusable controls at ${viewport.label}`,
  ).toEqual([]);

  if (contract.focused) {
    expect(
      geometry.visibleNavigation,
      `${contract.key} focused route must suppress ordinary RouteChrome`,
    ).toHaveLength(0);
  } else {
    expect(
      geometry.visibleNavigation,
      `${contract.key} must expose exactly one RouteChrome owner`,
    ).toHaveLength(1);
    const navigation = geometry.visibleNavigation[0];
    expect(["mobile", "rail", "header"]).toContain(navigation.variant);
    expect(navigation.box.left).toBeGreaterThanOrEqual(-1);
    expect(navigation.box.right).toBeLessThanOrEqual(geometry.clientWidth + 1);
  }
}

async function captureMinimumMobileEvidence(
  page: Page,
  testInfo: TestInfo,
  contract: RouteParityContract,
  appearance: ExplicitAppearance,
): Promise<void> {
  const baselineKey = `${contract.key}.${appearance}` as const;
  const baseline = MIN_MOBILE_VISUAL_BASELINES[baselineKey];
  const profileButton = page.getByRole("button", { name: "Открыть профиль" });
  const screenshot = await page.screenshot({
    animations: "disabled",
    caret: "hide",
    fullPage: true,
    mask: await profileButton.count() > 0 ? [profileButton] : [],
    scale: "css",
  });

  const actual = {
    width: screenshot.readUInt32BE(16),
    height: screenshot.readUInt32BE(20),
    sha256: createHash("sha256").update(screenshot).digest("hex"),
  };

  await testInfo.attach(`minimum-mobile-320x700-${contract.key}-${appearance}.png`, {
    body: screenshot,
    contentType: "image/png",
  });
  await testInfo.attach(`minimum-mobile-320x700-${contract.key}-${appearance}.json`, {
    body: Buffer.from(JSON.stringify({
      route: contract.path,
      routeKey: contract.key,
      appearance,
      responsiveViewport: { width: 320, height: 700 },
      canonicalMobileSourceViewport: { width: 390, height: 844 },
      sourceSemantics: "minimum-supported responsive runtime audit below the canonical 390×844 mobile OpenPencil/Figma source; no separate 320px design node",
      actual,
      approved: baseline,
    }, null, 2)),
    contentType: "application/json",
  });

  if (baseline.sha256 === "REVIEW_REQUIRED") {
    throw new Error(
      `${baselineKey}: REVIEW_REQUIRED exact Linux 320×700 evidence ${JSON.stringify(actual)}`,
    );
  }

  expect(
    actual,
    `${baselineKey}: exact Linux 320×700 fingerprint must match the manually reviewed evidence`,
  ).toEqual({
    width: baseline.width,
    height: baseline.height,
    sha256: baseline.sha256,
  });
}

async function captureTabletEvidence(
  page: Page,
  testInfo: TestInfo,
  contract: RouteParityContract,
  appearance: ExplicitAppearance,
): Promise<void> {
  const baselineKey = `${contract.key}.${appearance}` as const;
  const baseline = TABLET_VISUAL_BASELINES[baselineKey];
  const profileButton = page.getByRole("button", { name: "Открыть профиль" });
  const screenshot = await page.screenshot({
    animations: "disabled",
    caret: "hide",
    fullPage: true,
    mask: await profileButton.count() > 0 ? [profileButton] : [],
    scale: "css",
  });

  const actual = {
    width: screenshot.readUInt32BE(16),
    height: screenshot.readUInt32BE(20),
    sha256: createHash("sha256").update(screenshot).digest("hex"),
  };

  await testInfo.attach(`tablet-${contract.key}-${appearance}.png`, {
    body: screenshot,
    contentType: "image/png",
  });
  await testInfo.attach(`tablet-${contract.key}-${appearance}.json`, {
    body: Buffer.from(JSON.stringify({
      route: contract.path,
      routeKey: contract.key,
      appearance,
      responsiveViewport: { width: 768, height: 1024 },
      sourceSemantics: "responsive runtime interpolation between approved compact/desktop route sources; no separate tablet design node",
      actual,
      approved: baseline,
    }, null, 2)),
    contentType: "application/json",
  });

  expect(
    actual,
    `${baselineKey}: exact Linux 768×1024 fingerprint must match the manually reviewed evidence`,
  ).toEqual({
    width: baseline.width,
    height: baseline.height,
    sha256: baseline.sha256,
  });
}

async function captureDesktopEvidence(
  page: Page,
  testInfo: TestInfo,
  contract: RouteParityContract,
  appearance: ExplicitAppearance,
): Promise<void> {
  const baselineKey = `${contract.key}.${appearance}` as const;
  const baseline = DESKTOP_VISUAL_BASELINES[baselineKey];
  const profileButton = page.getByRole("button", { name: "Открыть профиль" });
  const screenshot = await page.screenshot({
    animations: "disabled",
    caret: "hide",
    fullPage: true,
    mask: await profileButton.count() > 0 ? [profileButton] : [],
    scale: "css",
  });

  const actual = {
    width: screenshot.readUInt32BE(16),
    height: screenshot.readUInt32BE(20),
    sha256: createHash("sha256").update(screenshot).digest("hex"),
  };

  await testInfo.attach(`desktop-1440x1024-${contract.key}-${appearance}.png`, {
    body: screenshot,
    contentType: "image/png",
  });
  await testInfo.attach(`desktop-1440x1024-${contract.key}-${appearance}.json`, {
    body: Buffer.from(JSON.stringify({
      route: contract.path,
      routeKey: contract.key,
      appearance,
      responsiveViewport: { width: 1440, height: 1024 },
      sourceSemantics: "desktop runtime acceptance for #205 using repository-owned OpenPencil route mapping; archived Figma identities are provenance/reference only",
      actual,
      approved: baseline,
    }, null, 2)),
    contentType: "application/json",
  });

  if (baseline.sha256 === "REVIEW_REQUIRED") {
    throw new Error(
      `${baselineKey}: REVIEW_REQUIRED exact Linux 1440×1024 evidence ${JSON.stringify(actual)}`,
    );
  }

  expect(
    actual,
    `${baselineKey}: exact Linux 1440×1024 fingerprint must match the manually reviewed evidence`,
  ).toEqual({
    width: baseline.width,
    height: baseline.height,
    sha256: baseline.sha256,
  });
}

test.describe("Issue #587 minimum-supported 320×700 route parity matrix", () => {
  test.describe.configure({ timeout: 90_000 });

  test.beforeEach(async ({ context, page }) => {
    await installDeterministicRuntime(page);
    await installQualityGateAPI(context);
  });

  for (const contract of ROUTE_PARITY_ROUTES) {
    for (const appearance of ["light", "dark"] as const) {
      test(`${contract.key} 320×700 ${appearance}`, async ({ context, page }, testInfo) => {
        test.skip(
          testInfo.project.name !== "visual-compact",
          "Issue #587 is the dedicated minimum-supported 320×700 responsive runtime evidence matrix.",
        );

        await page.setViewportSize({ width: 320, height: 700 });
        expect(page.viewportSize()).toEqual({ width: 320, height: 700 });
        testInfo.annotations.push({
          type: "responsive-source",
          description: `${contract.path} | 320×700 | ${appearance} | minimum supported runtime width below canonical 390×844 mobile source; no separate 320px design node`,
        });

        await installAppearance(page, appearance);
        const runtimeErrors = captureRuntimeErrors(page);
        await openParityRoute(contract, page, context);
        await settleParityRoute(page, appearance);
        await expectParityOwnership(page, contract, MIN_MOBILE_VIEWPORT, true);
        expect(runtimeErrors).toEqual([]);
        await captureMinimumMobileEvidence(page, testInfo, contract, appearance);
      });
    }
  }
});

test.describe("Issue #568 medium/tablet route parity matrix", () => {
  test.describe.configure({ timeout: 90_000 });

  test.beforeEach(async ({ context, page }) => {
    await installDeterministicRuntime(page);
    await installQualityGateAPI(context);
  });

  for (const contract of ROUTE_PARITY_ROUTES) {
    for (const appearance of ["light", "dark"] as const) {
      test(`${contract.key} 768×1024 ${appearance}`, async ({ context, page }, testInfo) => {
        test.skip(
          testInfo.project.name !== "visual-medium",
          "Issue #568 is the dedicated 768×1024 responsive runtime evidence matrix.",
        );

        expect(page.viewportSize()).toEqual({ width: 768, height: 1024 });
        testInfo.annotations.push({
          type: "responsive-source",
          description: `${contract.path} | 768×1024 | ${appearance} | no separate canonical tablet design node`,
        });

        await installAppearance(page, appearance);
        const runtimeErrors = captureRuntimeErrors(page);
        await openParityRoute(contract, page, context);
        await settleParityRoute(page, appearance);
        await expectParityOwnership(page, contract, TABLET_VIEWPORT);
        expect(runtimeErrors).toEqual([]);
        await captureTabletEvidence(page, testInfo, contract, appearance);
      });
    }
  }
});

test.describe("Issue #581 desktop 1440×1024 route parity matrix", () => {
  test.describe.configure({ timeout: 90_000 });

  test.beforeEach(async ({ context, page }) => {
    await installDeterministicRuntime(page);
    await installQualityGateAPI(context);
  });

  for (const contract of ROUTE_PARITY_ROUTES) {
    for (const appearance of ["light", "dark"] as const) {
      test(`${contract.key} 1440×1024 ${appearance}`, async ({ context, page }, testInfo) => {
        test.skip(
          testInfo.project.name !== "visual-desktop",
          "Issue #581 is the dedicated 1440×1024 desktop runtime evidence matrix.",
        );

        await page.setViewportSize({ width: 1440, height: 1024 });
        expect(page.viewportSize()).toEqual({ width: 1440, height: 1024 });
        testInfo.annotations.push({
          type: "responsive-source",
          description: `${contract.path} | 1440×1024 | ${appearance} | #205 desktop runtime acceptance`,
        });

        await installAppearance(page, appearance);
        const runtimeErrors = captureRuntimeErrors(page);
        await openParityRoute(contract, page, context);
        await settleParityRoute(page, appearance);
        await expectParityOwnership(page, contract, DESKTOP_VIEWPORT, true);
        expect(runtimeErrors).toEqual([]);
        await captureDesktopEvidence(page, testInfo, contract, appearance);
      });
    }
  }
});
