import type { LearningItem } from "./learning";

export const TECHNICAL_PHRASES: LearningItem[] = [
  {
    id: "phrase-root-cause",
    kind: "phrase",
    prompt: "We need to identify the root cause.",
    answer: "Нам нужно определить первопричину.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Incidents",
    examples: ["Before applying another workaround, we need to identify the root cause."],
    note: "root cause — первопричина, а не просто наблюдаемый симптом",
    status: "phrase",
    cloze: "We need to identify the _____ cause.",
  },
  {
    id: "phrase-reproducible",
    kind: "phrase",
    prompt: "The issue is reproducible in production.",
    answer: "Проблема воспроизводится в production.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Incidents",
    examples: ["The issue is reproducible in production but not in staging."],
    note: "reproducible — стабильно воспроизводимый",
    status: "phrase",
    cloze: "The issue is _____ in production.",
  },
  {
    id: "phrase-degraded",
    kind: "phrase",
    prompt: "The service is currently degraded.",
    answer: "Сервис сейчас работает с ухудшенным качеством.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Incidents",
    examples: ["The service is currently degraded, but requests are still being processed."],
    note: "degraded не обязательно означает полный outage",
    status: "phrase",
    cloze: "The service is currently _____.",
  },
  {
    id: "phrase-no-confirmed-root-cause",
    kind: "phrase",
    prompt: "There is no confirmed root cause yet.",
    answer: "Подтверждённой первопричины пока нет.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Incidents",
    examples: ["The incident is resolved, but there is no confirmed root cause yet."],
    note: "Подходит для аккуратного статуса без преждевременных выводов.",
    status: "phrase",
    cloze: "There is no _____ root cause yet.",
  },
  {
    id: "phrase-share-logs",
    kind: "phrase",
    prompt: "Could you share the relevant logs?",
    answer: "Можешь прислать относящиеся к проблеме логи?",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Troubleshooting",
    examples: ["Could you share the relevant logs and the exact timestamp?"],
    note: "relevant logs звучит точнее, чем просто logs",
    status: "phrase",
    cloze: "Could you share the _____ logs?",
  },
  {
    id: "phrase-walk-through",
    kind: "phrase",
    prompt: "Let's walk through the data flow.",
    answer: "Давайте пошагово разберём поток данных.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Architecture",
    examples: ["Let's walk through the data flow from NiFi to Greenplum."],
    note: "walk through — последовательно разобрать",
    status: "phrase",
    cloze: "Let's _____ through the data flow.",
  },
  {
    id: "phrase-backward-compatible",
    kind: "phrase",
    prompt: "This change is backward-compatible.",
    answer: "Это изменение обратно совместимо.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Architecture",
    examples: ["The schema change is backward-compatible with the current consumers."],
    note: "backward-compatible — совместимый с предыдущими версиями",
    status: "phrase",
    cloze: "This change is _____-compatible.",
  },
  {
    id: "phrase-database-migration",
    kind: "phrase",
    prompt: "This change requires a database migration.",
    answer: "Это изменение требует миграции базы данных.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Architecture",
    examples: ["This change requires a database migration before the new API can start."],
    note: "requires — требует, prerequisite — предварительное условие",
    status: "phrase",
    cloze: "This change requires a database _____.",
  },
  {
    id: "phrase-idempotent",
    kind: "phrase",
    prompt: "The job is idempotent.",
    answer: "Задача идемпотентна.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Data Engineering",
    examples: ["The job is idempotent, so it can be safely retried."],
    note: "idempotent — повторный запуск не меняет результат сверх первого применения",
    status: "phrase",
    cloze: "The job is _____.",
  },
  {
    id: "phrase-stale-data",
    kind: "phrase",
    prompt: "The data is stale.",
    answer: "Данные устарели.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Data Engineering",
    examples: ["The dashboard is available, but the data is stale."],
    note: "stale data — данные, которые не обновились вовремя",
    status: "phrase",
    cloze: "The data is _____.",
  },
  {
    id: "phrase-incomplete-data",
    kind: "phrase",
    prompt: "The dataset is incomplete.",
    answer: "Набор данных неполный.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Data Engineering",
    examples: ["The dataset is incomplete because one source system has not finished loading."],
    note: "dataset — набор данных; incomplete — неполный",
    status: "phrase",
    cloze: "The dataset is _____.",
  },
  {
    id: "phrase-resource-intensive",
    kind: "phrase",
    prompt: "The query is resource-intensive.",
    answer: "Запрос потребляет много ресурсов.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Data Engineering",
    examples: ["The query is resource-intensive and should not run during peak hours."],
    note: "resource-intensive — требующий значительных CPU, memory или I/O",
    status: "phrase",
    cloze: "The query is resource-_____.",
  },
  {
    id: "phrase-timeout",
    kind: "phrase",
    prompt: "The pipeline failed due to a timeout.",
    answer: "Пайплайн завершился ошибкой из-за таймаута.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Data Engineering",
    examples: ["The pipeline failed due to a timeout while reading from the source API."],
    note: "failed due to — завершился ошибкой из-за",
    status: "phrase",
    cloze: "The pipeline failed due to a _____.",
  },
  {
    id: "phrase-data-flow-bottleneck",
    kind: "phrase",
    prompt: "This stage is the main bottleneck.",
    answer: "Этот этап является основным узким местом.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Performance",
    examples: ["The database write stage is the main bottleneck in the data flow."],
    note: "bottleneck — узкое место, ограничивающее пропускную способность",
    status: "phrase",
    cloze: "This stage is the main _____.",
  },
  {
    id: "phrase-under-load",
    kind: "phrase",
    prompt: "We should test this under load.",
    answer: "Нам следует проверить это под нагрузкой.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Performance",
    examples: ["We should test this under load before enabling it in production."],
    note: "under load — в условиях нагрузки",
    status: "phrase",
    cloze: "We should test this under _____.",
  },
  {
    id: "phrase-acceptance-criteria",
    kind: "phrase",
    prompt: "Let's align on the acceptance criteria.",
    answer: "Давайте согласуем критерии приёмки.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Delivery",
    examples: ["Before implementation, let's align on the acceptance criteria."],
    note: "align on — согласовать общее понимание",
    status: "phrase",
    cloze: "Let's align on the acceptance _____.",
  },
  {
    id: "phrase-out-of-scope",
    kind: "phrase",
    prompt: "This is out of scope for this iteration.",
    answer: "Это не входит в объём текущей итерации.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Delivery",
    examples: ["Advanced analytics is out of scope for this iteration."],
    note: "out of scope — вне согласованного объёма работ",
    status: "phrase",
    cloze: "This is out of _____ for this iteration.",
  },
  {
    id: "phrase-next-steps",
    kind: "phrase",
    prompt: "What are the next steps?",
    answer: "Каковы следующие шаги?",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Delivery",
    examples: ["We have agreed on the design. What are the next steps?"],
    note: "Короткая нейтральная фраза для завершения обсуждения.",
    status: "phrase",
    cloze: "What are the next _____?",
  },
  {
    id: "phrase-eta",
    kind: "phrase",
    prompt: "Do we have an ETA for the fix?",
    answer: "Есть ли ожидаемый срок исправления?",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Delivery",
    examples: ["Do we have an ETA for the fix and the rollout plan?"],
    note: "ETA — estimated time of arrival; в работе означает ожидаемый срок",
    status: "phrase",
    cloze: "Do we have an _____ for the fix?",
  },
  {
    id: "phrase-deployed-staging",
    kind: "phrase",
    prompt: "The fix has been deployed to staging.",
    answer: "Исправление развёрнуто на staging.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Release",
    examples: ["The fix has been deployed to staging and is ready for verification."],
    note: "has been deployed — уже развёрнуто, результат актуален сейчас",
    status: "phrase",
    cloze: "The fix has been _____ to staging.",
  },
  {
    id: "phrase-roll-back",
    kind: "phrase",
    prompt: "We need to roll back the release.",
    answer: "Нам нужно откатить релиз.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Release",
    examples: ["The error rate is increasing, so we need to roll back the release."],
    note: "roll back — откатить изменение или релиз",
    status: "phrase",
    cloze: "We need to roll _____ the release.",
  },
  {
    id: "phrase-monitoring-alerting",
    kind: "phrase",
    prompt: "We should add monitoring and alerting.",
    answer: "Нам следует добавить мониторинг и оповещения.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Operations",
    examples: ["We should add monitoring and alerting before the production rollout."],
    note: "monitoring наблюдает состояние, alerting уведомляет об отклонениях",
    status: "phrase",
    cloze: "We should add monitoring and _____.",
  },
  {
    id: "phrase-clarify",
    kind: "phrase",
    prompt: "Could you clarify what you mean by that?",
    answer: "Можешь уточнить, что ты имеешь в виду?",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Communication",
    examples: ["Could you clarify what you mean by a complete reload?"],
    note: "Нейтральный способ запросить уточнение без конфронтации.",
    status: "phrase",
    cloze: "Could you _____ what you mean by that?",
  },
  {
    id: "phrase-correct-me",
    kind: "phrase",
    prompt: "Please correct me if I'm wrong.",
    answer: "Поправьте меня, если я ошибаюсь.",
    phonetic: "",
    partOfSpeech: "phrase",
    section: "phrase",
    topic: "Communication",
    examples: ["Please correct me if I'm wrong, but the consumer retries indefinitely."],
    note: "Используется перед осторожной формулировкой предположения.",
    status: "phrase",
    cloze: "Please _____ me if I'm wrong.",
  },
];
